set_property PACKAGE_PIN V12 [get_ports pin_rx_0]
set_property PACKAGE_PIN W16 [get_ports pin_tx_0]
set_property PACKAGE_PIN T17 [get_ports pin_rx_1]
set_property PACKAGE_PIN Y17 [get_ports pin_tx_1]
set_property IOSTANDARD LVCMOS33 [get_ports pin_rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports pin_rx_1]
set_property IOSTANDARD LVCMOS33 [get_ports pin_tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports pin_tx_1]